env: "dev"
http_server:
  address: "localhost:8080"
storage:
  db_name: "test_db"
auth_config_provider:
  google:
    redirect_url: "http://localhost:8080/api/v1/auth/google/callback"
    provider_id: "B80E81BI66XN6MU"
    provider_name: "google"
  jwt:
    provider_id: "4S4UXF650DBR6NR"
    provider_name: "jwt"


